version: '3.8'
services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
    volumes:
      - ./nginx-server.crt:/etc/nginx/ssl/nginx-server.crt
      - ./nginx-server.key:/etc/nginx/ssl/nginx-server.key
