apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-config.conf
          readOnly: true
        - name: tls-certs
          mountPath: /etc/nginx/certificate
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-map
      - name: tls-certs
        secret:
          secretName: tls-certs-secret