apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
        - name: iris
          image: amanroland/iris-app:0.0.1.RELEASE
          ports:
            - containerPort: 8000
