apiVersion: v1        # API version for the Kubernetes resource
kind: Service         # Specifies the type of resource, in this case, a Service
metadata:
  name: iris-svc      # Name of the Service resource

spec:
  selector:
    app: iris-app     # Selects Pods with the label 'app: iris_app'
  ports:
  - protocol: TCP     # Specifies the protocol for the service (TCP in this case)
    port: 8000        # Exposes the service on port 8000 on the Service's IP
    targetPort: 8000  # Routes traffic to Pods with the label 'app: iris_app' on port 8000
