apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
        - name: iris
          image: amanroland/iris-app:v0.0.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: slack-config
              mountPath: /home/blackrabbit/flask_app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: slack-config
          configMap:
            name: slack-config-map