apiVersion: v1         # API version for the Kubernetes resource
kind: Service          # Specifies the type of resource, in this case, a Service
metadata:
  name: nginx-svc      # Name of the Service resource
  labels:
    app: nginx         # Labels associated with the Service

spec:
  selector:
    app: nginx         # Selects Pods with the label 'app: nginx'
  ports:
    - protocol: TCP    # Specifies the protocol for the service (TCP in this case)
      name: http       # Name of the service port (http)
      port: 80         # Exposes the service on port 80 on the Service's IP
      targetPort: 80   # Routes traffic to Pods with the label 'app: nginx' on port 80
    - protocol: TCP    # Specifies the protocol for the service (TCP in this case)
      name: https      # Name of the service port (https)
      port: 443        # Exposes the service on port 443 on the Service's IP
      targetPort: 443  # Routes traffic to Pods with the label 'app: nginx' on port 443
  type: LoadBalancer   # Specifies the type of Service as LoadBalancer

